### ISSUE TITLE
Please Check this case in problem symmetric tree

### ISSUE THREAD

**Issue by ThongKun** [bobwei/algorithms#8]
Greeting Brother Bobwei,
I have been following you so far and I love your coding style. I am learning and imitating you. 
In this problem, I see that the case [1,0] is false, but your result is true. Please check it out. And I hope you notify me about this.
Grateful a lot.
![image](https://user-images.githubusercontent.com/5722599/88377250-07ba6c80-cdc9-11ea-93bb-d64bd28f3318.png)
https://github.com/bobwei/algorithms/blob/master/src/leetcode/symmetric-tree/index.js

**Comment by ThongKun** [comment]
`const defaultGetter = (key, obj) => {
    if (!obj[key]) return null
    return obj[key].val;
}`
here is my solution and it works. :D

**Comment by bobwei** [comment]
Hi @ThongKun , thank you very much for the idea. It would be even greater if you can send me a pull request. 😆

**Comment by ThongKun** [comment]
Hi @bobwei I did. Please check it.

**Comment by bobwei** [comment]
Hi @ThongKun, thanks for your pr. It's helpful, haha. BTW, I've changed my way to check the existence of property in an object. So I would use something like this.
```js
if (!('prop' in obj)) {
// prop not exists
}
```

In my previous code, I used `obj[prop]` to check existence. But in this case, it would be incorrect for the case of 0 like you mentioned. So good job for pointing this out!

**Comment by ThongKun** [comment]
Thank you, I also check your latest commit. :"D
